language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.txt --use-mirrors"
script: 
    - "py.test --cov=/home/talam/Desktop/programming/python/espn_py --cov-report=term --cov-report=html"